version: '3.4'

services:
  borg.web.clients.razor:
    container_name: borg.web.clients.razor
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44383
    ports:
      - "54764:80"
      - "44383:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro


  db:
    container_name: mssql
    environment:
      SA_PASSWORD: "Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - files:/sql/data
    ports:
      - "5433:1433"


  redis:
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - files:/redis/data


  rabbitmq:
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbituser
      - RABBITMQ_DEFAULT_PASS=Passw0rd
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - files:/rabbit/data



networks:
  default:


volumes:
  files: