version: '3.4'

services:
  borg.web.clients.razor:
    image: ${DOCKER_REGISTRY-}borgwebclientsrazor
    links:
      - db
      - redis
      - rabbitmq
    build:
      context: .
      dockerfile: ../../src/Clients/Borg.Web.Clients.Razor/Dockerfile


  db:
    image: "mcr.microsoft.com/mssql/server"


  redis:
   image: redis:latest

  rabbitmq:
    image: rabbitmq:3-management